apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: keycloak-mysql
  name: keycloak-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-mysql
#  strategy:
#    type: Recreate
  template:
    metadata:
      labels:
        app: keycloak-mysql
    spec:
      containers:
        - image: mysql:oraclelinux9
          name: keycloak-mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mysql_root_password
                  name: keycloak-mysql-secrets
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: keycloak-mysql-data
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "3Gi"
#      restartPolicy: Always
      volumes:
        - name: keycloak-mysql-data
          persistentVolumeClaim:
            claimName: keycloak-mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: keycloak-mysql
  name: keycloak-mysql
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: keycloak-mysql
---
apiVersion: v1
data:
  mysql_root_password: bXlzcWw=
kind: Secret
metadata:
  name: keycloak-mysql-secrets
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-mysql-pv
spec:
#  storageClassName: 'standard'
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /var/lib/mysql_keycloak_data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-mysql-pvc
spec:
#  storageClassName: 'standard'
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi