# mongodb.yaml
# Kubernetes manifest for the MongoDB Deployment, Service, PersistentVolume, and PersistentVolumeClaim

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo # Label for the Deployment
spec:
  replicas: 1 # Start with one replica for MongoDB (simple setup)
  selector:
    matchLabels:
      app: mongo # Selector to match pods
  template:
    metadata:
      labels:
        app: mongo # Label for the Pods
    spec:
      containers:
        - name: mongo # Container name
          image: mongo:noble # MongoDB Docker image
          imagePullPolicy: IfNotPresent # Pull if not already present
          ports:
            - containerPort: 27017 # The internal port MongoDB listens on
          # Optional: Add environment variables for MongoDB configuration (e.g., admin user/password)
          # env:
          #   - name: MONGO_INITDB_ROOT_USERNAME
          #     valueFrom:
          #       secretKeyRef:
          #         name: mongo-secrets # Name of the Secret containing credentials
          #         key: mongo_root_username # Key in the Secret
          #   - name: MONGO_INITDB_ROOT_PASSWORD
          #     valueFrom:
          #       secretKeyRef:
          #         name: mongo-secrets # Name of the Secret
          #         key: mongo_root_password # Key in the Secret
          volumeMounts:
            # Mount path for MongoDB data
            - mountPath: /data/db # Mount path inside the container (standard Mongo data path)
              name: mongo-storage # Name of the volume mount
          resources:
            # Define resource requests and limits (adjust based on expected data size and load)
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi" # Adjust based on usage
              cpu: "500m" # Adjust based on usage
      volumes:
        - name: mongo-storage # Volume name referenced in volumeMounts
          persistentVolumeClaim:
            claimName: mongo-pvc # Claim the PVC named mongo-pvc

---

# --- MongoDB Service ---
apiVersion: v1
kind: Service
metadata:
  name: mongo # The name of the Service - used by microservices (like product-service) to connect
  labels:
    app: mongo # Label for the Service
spec:
  selector:
    app: mongo # Selects pods with this label (the MongoDB Deployment pods)
  ports:
    - protocol: TCP
      port: 27017 # The port the Service will be accessible on *within* the cluster
      targetPort: 27017 # The containerPort on the pods that the Service targets
  type: ClusterIP # Default Service type, exposes the service on a cluster-internal IP

# To access MongoDB from outside the cluster (e.g., for a client tool),
# you would typically use kubectl port-forward.
# Example port-forward: kubectl port-forward svc/mongo 27017:27017

---

# --- MongoDB PersistentVolume ---
# WARNING: hostPath is NOT suitable for production or multi-node clusters!
# Data is tied to a specific node. Use dedicated storage solutions for production.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv # PV name
spec:
  # storageClassName: 'standard' # Optional: Use if you have a default storage class in kind.
  # If not, remove this or use a specific one.
  accessModes:
    - ReadWriteOnce # Can be mounted as read-write by a single node
  capacity:
    storage: 5Gi # Storage size for MongoDB data (adjust as needed)
  hostPath:
    # Path on the filesystem of the Kubernetes node (the kind container)
    # Ensure this directory exists and has appropriate permissions for the Mongo container user
    path: /var/lib/mongo_data # Using an absolute path is generally better

---

# --- MongoDB PersistentVolumeClaim ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc # PVC name (claimed by Deployment)
spec:
  # storageClassName: 'standard' # Optional: Must match the PV's storageClassName if used.
  # If PV has no storageClassName, remove this.
  accessModes:
    - ReadWriteOnce # Must match the PV's accessModes
  resources:
    requests:
      storage: 5Gi # Request storage (must match PV capacity or be less)
