# postgres-inventory.yaml
# Kubernetes manifest for the postgres-inventory Deployment, Service, PersistentVolume, and PersistentVolumeClaim

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-inventory-deployment
  labels:
    app: postgres-inventory # Label for the Deployment
spec:
  replicas: 1 # Start with one replica for the database
  selector:
    matchLabels:
      app: postgres-inventory # Selector to match pods
  template:
    metadata:
      labels:
        app: postgres-inventory # Label for the Pods
    spec:
      containers:
        - name: postgres-inventory # Container name
          image: postgres:13.21-alpine3.20 # PostgreSQL Docker image
          imagePullPolicy: IfNotPresent # Pull if not already present
          ports:
            - containerPort: 5432 # The internal port PostgreSQL listens on
          env:
            # Database Credentials and Name (Use Kubernetes Secrets for production!)
            - name: POSTGRES_DB
              value: inventory-service # Matches your docker-compose
            - name: POSTGRES_USER
              value: adeel # Matches your docker-compose
            - name: POSTGRES_PASSWORD
              value: password # Matches your docker-compose (INSECURE IN YAML - USE SECRETS)
            # Optional: Set PGDATA if different from default /var/lib/postgresql/data
            # - name: PGDATA
            #   value: /data/postgres # Matches your docker-compose volume mount path

          volumeMounts:
            # Mount path for PostgreSQL data (Matches the default or PGDATA env var)
            - mountPath: /var/lib/postgresql/data # Standard PostgreSQL data path
              name: postgres-inventory-storage # Name of the volume mount
          resources:
            # Define resource requests and limits (adjust based on expected data size and load)
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi" # Adjust based on usage
              cpu: "500m" # Adjust based on usage
      volumes:
        - name: postgres-inventory-storage # Volume name referenced in volumeMounts
          persistentVolumeClaim:
            claimName: postgres-inventory-pvc # Claim the PVC named postgres-inventory-pvc

---

# --- postgres-inventory Service ---
apiVersion: v1
kind: Service
metadata:
  name: postgres-inventory # The name of the Service - used by microservices (like inventory-service) to connect
  labels:
    app: postgres-inventory # Label for the Service
spec:
  selector:
    app: postgres-inventory # Selects pods with this label (the Deployment pods)
  ports:
    - protocol: TCP
      port: 5432 # The port the Service will be accessible on *within* the cluster
      targetPort: 5432 # The containerPort on the pods that the Service targets
  type: ClusterIP # Default Service type, exposes the service on a cluster-internal IP

# To access the database from outside the cluster (e.g., for a client tool),
# you would typically use kubectl port-forward.
# Example port-forward: kubectl port-forward svc/postgres-inventory 5432:5432

---

# --- postgres-inventory PersistentVolume ---
# WARNING: hostPath is NOT suitable for production or multi-node clusters!
# Data is tied to a specific node. Use dedicated storage solutions for production.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-inventory-pv # PV name
spec:
  # storageClassName: 'standard' # Optional: Use if you have a default storage class in kind.
  # If not, remove this or use a specific one.
  accessModes:
    - ReadWriteOnce # Can be mounted as read-write by a single node
  capacity:
    storage: 5Gi # Storage size for data (adjust as needed)
  hostPath:
    # Path on the filesystem of the Kubernetes node (the kind container)
    # Ensure this directory exists and has appropriate permissions for the Postgres container user
    path: /var/lib/postgres_inventory_data # Using an absolute path is generally better

---

# --- postgres-inventory PersistentVolumeClaim ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-inventory-pvc # PVC name (claimed by Deployment)
spec:
  # storageClassName: 'standard' # Optional: Must match the PV's storageClassName if used.
  # If PV has no storageClassName, remove this.
  accessModes:
    - ReadWriteOnce # Must match the PV's accessModes
  resources:
    requests:
      storage: 5Gi # Request storage (must match PV capacity or be less)
